### ISSUE TITLE
deleteでtransaction.rollbackができない

### ISSUE THREAD

**Issue by h-otter** [n0stack/n0stack#114]
qemuプロセスを削除したあとにする操作がない

**Comment by kyontan** [comment]
qemuプロセスの削除に関するエラーも含め、 rollbackができない操作のエラーハンドリングとして、以下の2つが考えられます

1. プロセスが存在しなかった場合など、特に放置しても問題がないエラー
2. プロセスの kill に失敗するなど、放置すると問題があるエラー

後者は管理者による対応が必要ですが、前者は `ignore_error: true` で対処できますし、管理用に `hard_delete` ないし `hard` のようなパラメータを付けてもよいかと思います

**Comment by h-otter** [comment]
実体が削除されていても無視をして、メタデータだけロールバックする

**Comment by h-otter** [comment]
fixed on 46d3534ad9aff52ccc5812971486ce9d7b3c87a2 (blockstorage), c98268f35433ececdc63e2ee9addf36b153332aa (virtual machine)

block storageの実装は、実体のロールバックやエラーの無視がないため実質ロールバックはできていない
