### ISSUE TITLE
lockでエラーを速攻返してもいいのか

### ISSUE THREAD

**Issue by h-otter** [n0stack/n0stack#115]

**Comment by kyontan** [comment]
途中でロックの確保に失敗すると不便なケースが大半だと考えられるので、 `waitUntilLock` のようなインタフェースを実装して、基本的に待つようにするべきだと思います

**Comment by h-otter** [comment]
Createはロックできない時点で他の人が作っているはずで、ユーザーの不備なはずなのですぐ返す
Deleteはユーザーの不備ではないのでまつ、少し危険な気がするので安全側に倒すなら待たないほうがいい気がするが :thinking: 

拡張メソッドは基本的に他のユーザーがロックをかけている可能性があるので、待つ
