### ISSUE TITLE
download apiで存在しないブロックストレージを指定した場合、200を返してしまう

### ISSUE THREAD

**Issue by gurapomu** [n0stack/n0stack#143]
source_url: http://172.16.1.35:8080/api/v0/block_storage/download/$not_exist_file
みたいな感じにするとからのblockStorageができる

**Comment by h-otter** [comment]
fixed on 5816e03f2a07f686add29ad73c04ccf2cd12cd9e

**Comment by h-otter** [comment]
fixed on a682dc908e8e268dc43557a751a693579444cb57 again
