### ISSUE TITLE
imageを削除したときにblockstorageをAVAILABLEにし忘れている

### ISSUE THREAD

**Issue by h-otter** [n0stack/n0stack#151]

**Comment by kyontan** [comment]
多分ちゃんと動いてると思いますが…… (手元で確認した限りでは)

`DeleteImage`

https://github.com/n0stack/n0stack/blob/2cc94d3d59ce6cb1f04bd487e87000b7c0a765a3/n0core/pkg/api/deployment/image/api.go#L112-L117

`UnregisterBlockStorage`

https://github.com/n0stack/n0stack/blob/2cc94d3d59ce6cb1f04bd487e87000b7c0a765a3/n0core/pkg/api/deployment/image/api.go#L184-L187

**Comment by h-otter** [comment]
また、再現したらreopenします
