### ISSUE TITLE
namespaceやプロジェクトのような名前空間の実装

### ISSUE THREAD

**Issue by h-otter** [n0stack/n0stack#215]
複数のユーザーが使う基盤では管理を簡単にするために名前空間などを区切りたいがなかなかいい抽象化が思いつかない

例えばすべてのリソースにnamespaceフィールドのようなものを作った場合、すべてのリソースで名前空間を気にして実装する必要がある。また、認証をどこでやるかや実装の複雑さを考えると難しいと考えられる。

しかし、他にいい案も思いつかない

**Comment by h-otter** [comment]
iam/project を作った

**Comment by kyontan** [comment]
hoge
